import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { loadPatchSpec } from '../spec.js';
import type { PatchSpec } from '../types.js';

type InstalledManifest = {
  schema: string;
  patches: Array<{ id: string; version: string; installed_at: string }>;
};

type RuntimePatch = Pick<PatchSpec, 'id' | 'name' | 'version' | 'intervention'>;

function runtimeSource(patches: RuntimePatch[]): string {
  return `// Generated by RMDY. Regenerate with: rmdy install AP-ID --runtime openai-agents
import { ToolGuardrailFunctionOutputFactory, defineToolInputGuardrail } from '@openai/agents';

export const installedPatches = Object.freeze(${JSON.stringify(patches, null, 2)});

function stable(value) {
  if (Array.isArray(value)) return '[' + value.map(stable).join(',') + ']';
  if (value && typeof value === 'object') {
    return '{' + Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => key + ':' + stable(item)).join(',') + '}';
  }
  return JSON.stringify(value);
}

function parseArguments(value) {
  try {
    const parsed = JSON.parse(value || '{}');
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

export function createAgentPatchRuntime(options = {}) {
  const stateByRun = new WeakMap();
  const fallbackState = { loops: new Map() };
  const stateFor = (context) => {
    if (!context || (typeof context !== 'object' && typeof context !== 'function')) return fallbackState;
    let state = stateByRun.get(context);
    if (!state) {
      state = { loops: new Map() };
      stateByRun.set(context, state);
    }
    return state;
  };

  const guardrail = defineToolInputGuardrail({
    name: 'agent_patch_runtime',
    run: async ({ toolCall, context }) => {
      const args = parseArguments(toolCall.arguments);
      const normalizedArgs = Object.fromEntries(Object.entries(args).map(([key, value]) => [key.toLowerCase(), value]));
      for (const patch of installedPatches) {
        const intervention = patch.intervention;
        if (intervention.type === 'require_tool_arguments' && toolCall.name === intervention.tool) {
          const missing = intervention.required.filter((field) => {
            const value = normalizedArgs[field.toLowerCase()];
            return value === '' || value === null || value === undefined;
          });
          if (missing.length) {
            const message = '[' + patch.id + '] Tool call blocked. Resolve required arguments before retrying: ' + missing.join(', ') + '.';
            options.onDecision?.({ patchId: patch.id, decision: 'blocked', tool: toolCall.name, reason: 'missing_arguments', missing });
            return ToolGuardrailFunctionOutputFactory.rejectContent(message, { patchId: patch.id, missing });
          }
        }
        if (intervention.type === 'limit_repeated_tool_calls') {
          const state = stateFor(context);
          const loopState = state.loops.get(patch.id) ?? { lastFingerprint: '', repetitions: 0 };
          const fingerprint = toolCall.name + ':' + stable(args);
          if (loopState.lastFingerprint === fingerprint) loopState.repetitions += 1;
          else {
            loopState.lastFingerprint = fingerprint;
            loopState.repetitions = 1;
          }
          state.loops.set(patch.id, loopState);
          if (loopState.repetitions >= intervention.threshold) {
            const direction = intervention.on_failure === 'hand_back'
              ? 'Hand control back to the user.'
              : 'Re-plan with materially different arguments or a different tool.';
            const message = '[' + patch.id + '] Repeated identical tool call blocked after ' + loopState.repetitions + ' attempts. ' + direction;
            options.onDecision?.({ patchId: patch.id, decision: 'blocked', tool: toolCall.name, reason: 'repeated_tool_call', repetitions: loopState.repetitions });
            return ToolGuardrailFunctionOutputFactory.rejectContent(message, { patchId: patch.id, repetitions: loopState.repetitions });
          }
        }
      }
      options.onDecision?.({ decision: 'allowed', tool: toolCall.name });
      return ToolGuardrailFunctionOutputFactory.allow();
    },
  });

  const applyAgentPatches = (tools) => {
    if (!Array.isArray(tools)) throw new TypeError('applyAgentPatches expects an array of OpenAI Agents SDK tools.');
    return tools.map((tool) => tool?.type === 'function'
      ? { ...tool, inputGuardrails: [guardrail, ...(tool.inputGuardrails ?? [])] }
      : tool);
  };

  return { applyAgentPatches, guardrail, installedPatches };
}

const defaultRuntime = createAgentPatchRuntime();
export const applyAgentPatches = defaultRuntime.applyAgentPatches;
`;
}

const declarations = `export type AgentPatchDecision = {
  patchId?: string;
  decision: 'allowed' | 'blocked';
  tool: string;
  reason?: 'missing_arguments' | 'repeated_tool_call';
  missing?: string[];
  repetitions?: number;
};
export type AgentPatchRuntimeOptions = { onDecision?: (event: AgentPatchDecision) => void };
export type FunctionToolLike = { type?: string; inputGuardrails?: unknown[]; [key: string]: unknown };
export declare const installedPatches: readonly unknown[];
export declare function createAgentPatchRuntime(options?: AgentPatchRuntimeOptions): {
  applyAgentPatches: <T extends FunctionToolLike>(tools: T[]) => T[];
  guardrail: unknown;
  installedPatches: readonly unknown[];
};
export declare const applyAgentPatches: <T extends FunctionToolLike>(tools: T[]) => T[];
`;

function runtimeReadme(patches: RuntimePatch[]): string {
  return `# OpenAI Agents SDK adapter

Installed patches: ${patches.map((patch) => `${patch.id}@${patch.version}`).join(', ')}

This adapter uses OpenAI Agents SDK function-tool input guardrails. It blocks a rejected call before the custom function executes and returns a model-visible re-planning instruction.

\`\`\`js
import { Agent, run, tool } from '@openai/agents';
import { z } from 'zod';
import { applyAgentPatches } from './.apatch/runtime/openai-agents.mjs';

const searchInventory = tool({
  name: 'inventory_search',
  description: 'Search inventory',
  parameters: z.object({ query: z.string(), delivery: z.string().optional() }),
  execute: async ({ query, delivery }) => ({ query, delivery, results: [] }),
});

const agent = new Agent({
  name: 'Shopping agent',
  instructions: 'Search inventory and change strategy when a tool call makes no progress.',
  tools: applyAgentPatches([searchInventory]),
});

const result = await run(agent, 'Find running shoes that arrive today.', {
  toolExecution: { maxFunctionToolConcurrency: 1 },
});
console.log(result.finalOutput);
\`\`\`

Install the SDK in the target project with \`npm install @openai/agents zod\`.

Limit: OpenAI Agents SDK tool guardrails apply to custom function tools. Hosted tools, built-in execution tools, handoffs, and \`agent.asTool()\` do not pass through this guardrail pipeline.
`;
}

export async function installOpenAIAgentsRuntime(destinationRoot: string, manifest: InstalledManifest): Promise<{ adapterPath: string; patches: RuntimePatch[] }> {
  const patches: RuntimePatch[] = [];
  for (const entry of manifest.patches) {
    const specPath = path.join(destinationRoot, '.apatch', 'patches', entry.id, 'patch.yaml');
    const { spec } = await loadPatchSpec(specPath);
    patches.push({ id: spec.id, name: spec.name, version: spec.version, intervention: spec.intervention });
  }
  if (patches.length === 0) throw new Error('Install at least one patch before generating a runtime adapter.');
  const runtimeDirectory = path.join(destinationRoot, '.apatch', 'runtime');
  const adapterPath = path.join(runtimeDirectory, 'openai-agents.mjs');
  await mkdir(runtimeDirectory, { recursive: true });
  await writeFile(adapterPath, runtimeSource(patches), 'utf8');
  await writeFile(path.join(runtimeDirectory, 'openai-agents.d.ts'), declarations, 'utf8');
  await writeFile(path.join(runtimeDirectory, 'README.md'), runtimeReadme(patches), 'utf8');
  return { adapterPath, patches };
}

export async function readInstalledManifest(destinationRoot: string): Promise<InstalledManifest> {
  const manifestPath = path.join(destinationRoot, '.apatch', 'installed.json');
  return JSON.parse(await readFile(manifestPath, 'utf8')) as InstalledManifest;
}
